source activate torch
python train.py -cpk JointLateClusterSoftStyle5_G -tb 1 -exp 1 -modelKwargs '{"lambda_id": 0.1, "argmax": 1, "some_grad_flag": 1, "train_only": 1, "max_num_speakers": 25}' -model JointLateClusterSoftStyle5_G -note mixstage_fs_t1 -speaker '["oliver"]' -save_dir save7/cl/t1/mixstage_fs_t1/oliver -modalities '["pose/normalize", "audio/log_mel_400", "text/tokens"]' -fs_new '[15, 15, 15]' -input_modalities '["audio/log_mel_400", "text/tokens"]' -output_modalities '["pose/normalize"]' -gan 1 -loss L1Loss -window_hop 5 -render 0 -batch_size 16 -num_epochs 2000 -stop_thresh 3 -overfit 0 -early_stopping 0 -dev_key dev_spatialNorm -num_clusters 8 -feats '["pose", "velocity", "speed"]' -fewshot_seed 1 -k_shot 140 -cache 1 -no_grad 0 -repeat_text 0
source activate torch
python train.py -cpk JointLateClusterSoftStyle5_G -tb 1 -exp 1 -modelKwargs '{"lambda_id": 0.1, "argmax": 1, "some_grad_flag": 1, "train_only": 1, "max_num_speakers": 25}' -model JointLateClusterSoftStyle5_G -note mixstage_fs_t1 -speaker '["maher"]' -save_dir save7/cl/t1/mixstage_fs_t1/maher -modalities '["pose/normalize", "audio/log_mel_400", "text/tokens"]' -fs_new '[15, 15, 15]' -input_modalities '["audio/log_mel_400", "text/tokens"]' -output_modalities '["pose/normalize"]' -gan 1 -loss L1Loss -window_hop 5 -render 0 -batch_size 16 -num_epochs 2000 -stop_thresh 3 -overfit 0 -early_stopping 0 -dev_key dev_spatialNorm -num_clusters 8 -feats '["pose", "velocity", "speed"]' -fewshot_seed 1 -k_shot 140 -cache 1 -no_grad 0 -repeat_text 0
source activate torch
python train.py -cpk JointLateClusterSoftStyle5_G -tb 1 -exp 1 -modelKwargs '{"lambda_id": 0.1, "argmax": 1, "some_grad_flag": 1, "train_only": 1, "max_num_speakers": 25}' -model JointLateClusterSoftStyle5_G -note mixstage_fs_t1 -speaker '["chemistry"]' -save_dir save7/cl/t1/mixstage_fs_t1/chemistry -modalities '["pose/normalize", "audio/log_mel_400", "text/tokens"]' -fs_new '[15, 15, 15]' -input_modalities '["audio/log_mel_400", "text/tokens"]' -output_modalities '["pose/normalize"]' -gan 1 -loss L1Loss -window_hop 5 -render 0 -batch_size 16 -num_epochs 2000 -stop_thresh 3 -overfit 0 -early_stopping 0 -dev_key dev_spatialNorm -num_clusters 8 -feats '["pose", "velocity", "speed"]' -fewshot_seed 1 -k_shot 140 -cache 1 -no_grad 0 -repeat_text 0
source activate torch
python train.py -cpk JointLateClusterSoftStyle5_G -tb 1 -exp 1 -modelKwargs '{"lambda_id": 0.1, "argmax": 1, "some_grad_flag": 1, "train_only": 1, "max_num_speakers": 25}' -model JointLateClusterSoftStyle5_G -note mixstage_fs_t1 -speaker '["ytch_prof"]' -save_dir save7/cl/t1/mixstage_fs_t1/ytch_prof -modalities '["pose/normalize", "audio/log_mel_400", "text/tokens"]' -fs_new '[15, 15, 15]' -input_modalities '["audio/log_mel_400", "text/tokens"]' -output_modalities '["pose/normalize"]' -gan 1 -loss L1Loss -window_hop 5 -render 0 -batch_size 16 -num_epochs 2000 -stop_thresh 3 -overfit 0 -early_stopping 0 -dev_key dev_spatialNorm -num_clusters 8 -feats '["pose", "velocity", "speed"]' -fewshot_seed 1 -k_shot 140 -cache 1 -no_grad 0 -repeat_text 0
source activate torch
python train.py -cpk JointLateClusterSoftStyle5_G -tb 1 -exp 1 -modelKwargs '{"lambda_id": 0.1, "argmax": 1, "some_grad_flag": 1, "train_only": 1, "max_num_speakers": 25}' -model JointLateClusterSoftStyle5_G -note mixstage_fs_t1 -speaker '["lec_evol"]' -save_dir save7/cl/t1/mixstage_fs_t1/lec_evol -modalities '["pose/normalize", "audio/log_mel_400", "text/tokens"]' -fs_new '[15, 15, 15]' -input_modalities '["audio/log_mel_400", "text/tokens"]' -output_modalities '["pose/normalize"]' -gan 1 -loss L1Loss -window_hop 5 -render 0 -batch_size 16 -num_epochs 2000 -stop_thresh 3 -overfit 0 -early_stopping 0 -dev_key dev_spatialNorm -num_clusters 8 -feats '["pose", "velocity", "speed"]' -fewshot_seed 1 -k_shot 140 -cache 1 -no_grad 0 -repeat_text 0
