source activate torch
python train.py -cpk StyleDiffGAN3_G -tb 1 -exp 1 -modelKwargs '{"tgt_train_ratio": 1, "get_pretrained_D": 1}' -model StyleDiffGAN3_G -fewshot_seed 1 -k_shot 28 -note diffgan_no-replay-fs -speaker '[["chemistry"], ["chemistry", "maher"]]' -save_dir save7/cl/t2/no-replay-fs/diffgan_no-replay-fs/28/chemistry-maher/1 -pretrained_model_weights save7/cl/t1/mixstage_t1/chemistry/"$(ls save7/cl/t1/mixstage_t1/chemistry | grep weights | tail -1)" -modalities '["pose/normalize", "audio/log_mel_400", "text/tokens"]' -fs_new '[15, 15, 15]' -input_modalities '["audio/log_mel_400", "text/tokens"]' -output_modalities '["pose/normalize"]' -gan diffgan -loss L1Loss -window_hop 5 -render 0 -batch_size 32 -num_epochs 20 -stop_thresh 3 -overfit 1 -early_stopping 1 -dev_key dev_FID -num_clusters 8 -feats '["pose", "velocity", "speed"]' -num_iters 200 -num_training_iters 200 -no_grad 0 -repeat_text 0 -dg_iter_ratio 1 -update_D_prob_flag 0 -cache 1 -replay no-replay-fs -paradigm no_src_tgt || exit
source activate torch
python train.py -cpk StyleDiffGAN3_G -tb 1 -exp 1 -modelKwargs '{"tgt_train_ratio": 1, "get_pretrained_D": 1}' -model StyleDiffGAN3_G -fewshot_seed 1 -k_shot 140 -note diffgan_no-replay-fs -speaker '[["chemistry"], ["chemistry", "maher"]]' -save_dir save7/cl/t2/no-replay-fs/diffgan_no-replay-fs/140/chemistry-maher/1 -pretrained_model_weights save7/cl/t1/mixstage_t1/chemistry/"$(ls save7/cl/t1/mixstage_t1/chemistry | grep weights | tail -1)" -modalities '["pose/normalize", "audio/log_mel_400", "text/tokens"]' -fs_new '[15, 15, 15]' -input_modalities '["audio/log_mel_400", "text/tokens"]' -output_modalities '["pose/normalize"]' -gan diffgan -loss L1Loss -window_hop 5 -render 0 -batch_size 32 -num_epochs 20 -stop_thresh 3 -overfit 1 -early_stopping 1 -dev_key dev_FID -num_clusters 8 -feats '["pose", "velocity", "speed"]' -num_iters 200 -num_training_iters 200 -no_grad 0 -repeat_text 0 -dg_iter_ratio 1 -update_D_prob_flag 0 -cache 1 -replay no-replay-fs -paradigm no_src_tgt || exit
source activate torch
python train.py -cpk StyleDiffGAN3_G -tb 1 -exp 1 -modelKwargs '{"tgt_train_ratio": 1, "get_pretrained_D": 1}' -model StyleDiffGAN3_G -fewshot_seed 2 -k_shot 28 -note diffgan_no-replay-fs -speaker '[["chemistry"], ["chemistry", "maher"]]' -save_dir save7/cl/t2/no-replay-fs/diffgan_no-replay-fs/28/chemistry-maher/2 -pretrained_model_weights save7/cl/t1/mixstage_t1/chemistry/"$(ls save7/cl/t1/mixstage_t1/chemistry | grep weights | tail -1)" -modalities '["pose/normalize", "audio/log_mel_400", "text/tokens"]' -fs_new '[15, 15, 15]' -input_modalities '["audio/log_mel_400", "text/tokens"]' -output_modalities '["pose/normalize"]' -gan diffgan -loss L1Loss -window_hop 5 -render 0 -batch_size 32 -num_epochs 20 -stop_thresh 3 -overfit 1 -early_stopping 1 -dev_key dev_FID -num_clusters 8 -feats '["pose", "velocity", "speed"]' -num_iters 200 -num_training_iters 200 -no_grad 0 -repeat_text 0 -dg_iter_ratio 1 -update_D_prob_flag 0 -cache 1 -replay no-replay-fs -paradigm no_src_tgt || exit
source activate torch
python train.py -cpk StyleDiffGAN3_G -tb 1 -exp 1 -modelKwargs '{"tgt_train_ratio": 1, "get_pretrained_D": 1}' -model StyleDiffGAN3_G -fewshot_seed 2 -k_shot 140 -note diffgan_no-replay-fs -speaker '[["chemistry"], ["chemistry", "maher"]]' -save_dir save7/cl/t2/no-replay-fs/diffgan_no-replay-fs/140/chemistry-maher/2 -pretrained_model_weights save7/cl/t1/mixstage_t1/chemistry/"$(ls save7/cl/t1/mixstage_t1/chemistry | grep weights | tail -1)" -modalities '["pose/normalize", "audio/log_mel_400", "text/tokens"]' -fs_new '[15, 15, 15]' -input_modalities '["audio/log_mel_400", "text/tokens"]' -output_modalities '["pose/normalize"]' -gan diffgan -loss L1Loss -window_hop 5 -render 0 -batch_size 32 -num_epochs 20 -stop_thresh 3 -overfit 1 -early_stopping 1 -dev_key dev_FID -num_clusters 8 -feats '["pose", "velocity", "speed"]' -num_iters 200 -num_training_iters 200 -no_grad 0 -repeat_text 0 -dg_iter_ratio 1 -update_D_prob_flag 0 -cache 1 -replay no-replay-fs -paradigm no_src_tgt || exit
source activate torch
python train.py -cpk StyleDiffGAN3_G -tb 1 -exp 1 -modelKwargs '{"tgt_train_ratio": 1, "get_pretrained_D": 1}' -model StyleDiffGAN3_G -fewshot_seed 3 -k_shot 28 -note diffgan_no-replay-fs -speaker '[["chemistry"], ["chemistry", "maher"]]' -save_dir save7/cl/t2/no-replay-fs/diffgan_no-replay-fs/28/chemistry-maher/3 -pretrained_model_weights save7/cl/t1/mixstage_t1/chemistry/"$(ls save7/cl/t1/mixstage_t1/chemistry | grep weights | tail -1)" -modalities '["pose/normalize", "audio/log_mel_400", "text/tokens"]' -fs_new '[15, 15, 15]' -input_modalities '["audio/log_mel_400", "text/tokens"]' -output_modalities '["pose/normalize"]' -gan diffgan -loss L1Loss -window_hop 5 -render 0 -batch_size 32 -num_epochs 20 -stop_thresh 3 -overfit 1 -early_stopping 1 -dev_key dev_FID -num_clusters 8 -feats '["pose", "velocity", "speed"]' -num_iters 200 -num_training_iters 200 -no_grad 0 -repeat_text 0 -dg_iter_ratio 1 -update_D_prob_flag 0 -cache 1 -replay no-replay-fs -paradigm no_src_tgt || exit
source activate torch
python train.py -cpk StyleDiffGAN3_G -tb 1 -exp 1 -modelKwargs '{"tgt_train_ratio": 1, "get_pretrained_D": 1}' -model StyleDiffGAN3_G -fewshot_seed 3 -k_shot 140 -note diffgan_no-replay-fs -speaker '[["chemistry"], ["chemistry", "maher"]]' -save_dir save7/cl/t2/no-replay-fs/diffgan_no-replay-fs/140/chemistry-maher/3 -pretrained_model_weights save7/cl/t1/mixstage_t1/chemistry/"$(ls save7/cl/t1/mixstage_t1/chemistry | grep weights | tail -1)" -modalities '["pose/normalize", "audio/log_mel_400", "text/tokens"]' -fs_new '[15, 15, 15]' -input_modalities '["audio/log_mel_400", "text/tokens"]' -output_modalities '["pose/normalize"]' -gan diffgan -loss L1Loss -window_hop 5 -render 0 -batch_size 32 -num_epochs 20 -stop_thresh 3 -overfit 1 -early_stopping 1 -dev_key dev_FID -num_clusters 8 -feats '["pose", "velocity", "speed"]' -num_iters 200 -num_training_iters 200 -no_grad 0 -repeat_text 0 -dg_iter_ratio 1 -update_D_prob_flag 0 -cache 1 -replay no-replay-fs -paradigm no_src_tgt || exit
